name: example-config
on:
  push:
    branches:
      - "master"
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  start:
    # example where we pass custom base URL
    runs-on: nscloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create a k8s cluster with Namespace
        id: create-cluster
        uses: namespacelabs/nscloud-cluster-action@v0

      - name: Deploy NGINX
        run: |
          kubectl run nginx --image=nginx
          kubectl expose pod nginx --type=LoadBalancer --port=80

      - name: Expose application
        run: |
          nsc expose kubernetes ${{ steps.create-cluster.outputs.instance-id }} \
            --namespace=default \
            --service=nginx \
            --name=demo-ingress-name \
            --output json | jq -r .url

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: example
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3333"
          config: baseUrl=http://localhost:3333
